### ISSUE TITLE
panic on login

### ISSUE THREAD

**Issue by mtibben** [99designs/aws-vault#114]
Using aws-vault 3.7.0
```
$ aws-vault login home
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4006cd2]

goroutine 1 [running]:
panic(0x447f2a0, 0xc4200120d0)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
main.getUserName(0xc420131520, 0x14, 0xc420136690, 0x28, 0x0, 0x0, 0x0, 0x0, 0xc420116a00, 0x47, ...)
	/Users/michael/src/github.com/99designs/aws-vault/login.go:204 +0x202
main.getFederationToken(0xc420131520, 0x14, 0xc420136690, 0x28, 0x0, 0x0, 0x0, 0x0, 0x274a48a78000, 0x0, ...)
	/Users/michael/src/github.com/99designs/aws-vault/login.go:182 +0x364
main.LoginCommand(0xc4200b8870, 0x7fff5fbff4c0, 0x4, 0x476c920, 0xc420113860, 0x0, 0x0, 0x45465b0, 0x0, 0x274a48a78000, ...)
	/Users/michael/src/github.com/99designs/aws-vault/login.go:76 +0x1967
main.configureLoginCommand.func1(0xc42009ce10, 0x402349a, 0x448c7a0)
	/Users/michael/src/github.com/99designs/aws-vault/main.go:181 +0xb5
github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc4200b6498, 0xc42009ce10, 0x0, 0x0)
	/Users/michael/src/github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin.v2/actions.go:28 +0x58
github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc4200b8870, 0xc42009ce10, 0x0, 0x0)
	/Users/michael/src/github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:554 +0x126
github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc4200b8870, 0xc42009ce10, 0xc420013fd0, 0x1, 0x1, 0x0, 0x0, 0x1, 0xc4200e72c0)
	/Users/michael/src/github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:390 +0x8f
github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc4200b8870, 0xc42000c160, 0x2, 0x2, 0x1, 0xc42002e180, 0x0, 0x1)
	/Users/michael/src/github.com/99designs/aws-vault/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:222 +0x202
main.run(0xc42000c160, 0x2, 0x2, 0x4546da8)
	/Users/michael/src/github.com/99designs/aws-vault/main.go:239 +0x9e2
main.main()
	/Users/michael/src/github.com/99designs/aws-vault/main.go:245 +0x72
```

**Comment by lox** [comment]
Interesting, looks like GetUser isn't returning a username? I wonder what the error is, shame we are swallowing it. 

What type of credentials are you trying to use @mtibben? Federated or assumeRole?

**Comment by gregwebs** [comment]
I saw this when I tried with a defunct user.

**Comment by lox** [comment]
As in a user that doesn't exist in IAM?

**Comment by gregwebs** [comment]
I believe the user did exist in IAM but the account is closed now.
