### ISSUE TITLE
`--server` not working  on linux

### ISSUE THREAD

**Issue by frezbo** [99designs/aws-vault#255]
```
~ (aws:gov)(kc)$ aws-vault exec --server ${AWS_PROFILE} -- bash
[sudo] password for frezbo: 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/99designs/aws-vault/vendor/github.com/aulanov/go%2edbus.sessionBusPlatform(0x996211, 0x18, 0x0)
	/Users/michael/src/github.com/99designs/aws-vault/vendor/github.com/aulanov/go.dbus/conn_other.go:26 +0x1ff
github.com/99designs/aws-vault/vendor/github.com/aulanov/go%2edbus.SessionBusPrivate(0x8, 0x9adfa0, 0xc420051ec0)
	/Users/michael/src/github.com/99designs/aws-vault/vendor/github.com/aulanov/go.dbus/conn.go:99 +0xb0
github.com/99designs/aws-vault/vendor/github.com/aulanov/go%2edbus.SessionBus(0x0, 0x0, 0x0)
	/Users/michael/src/github.com/99designs/aws-vault/vendor/github.com/aulanov/go.dbus/conn.go:76 +0xad
github.com/99designs/aws-vault/vendor/github.com/99designs/keyring.init.1()
	/Users/michael/src/github.com/99designs/aws-vault/vendor/github.com/99designs/keyring/kwallet.go:18 +0x26

~ (aws:gov)(kc)$ 

```

OS Settings:
```
~ (aws:gov)(kc)$ printenv AWS_PROFILE
gov
~ (aws:gov)(kc)$ printenv AWS_VAULT_BACKEND
secret-service
~ (aws:gov)(kc)$ cat /etc/*-release
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)

```

**Comment by Diegow3b** [comment]
I'm having the same problem
