### ISSUE TITLE
Strange "Credential named assume-role-with-web-identity not found." error

### ISSUE THREAD

**Issue by Govinda-Fichtner** [99designs/aws-vault#442]
I do get a strange error after executing the following aws-vault command:
```
aws-vault --debug exec --no-session vera-git -- aws sts get-caller-identity --debug
2019/11/02 10:47:05 [keyring] Considering backends: [keychain pass file]
2019/11/02 10:47:05 Loading config file /Users/fichtner/.aws/config
2019/11/02 10:47:05 Parsing config file /Users/fichtner/.aws/config
2019/11/02 10:47:05 Skipping session token and using master credentials directly
2019/11/02 10:47:05 Looking up keyring for vera
2019/11/02 10:47:05 [keyring] Querying keychain for service="aws-vault", account="vera", keychain="aws-vault.keychain"
2019/11/02 10:47:09 [keyring] Found item "aws-vault (vera)"
2019/11/02 10:47:09 Using region "eu-west-1" from profile
Enter token for arn:aws:iam::511237493963:mfa/vera: 830106
2019/11/02 10:47:15 Assuming role arn:aws:iam::753846010638:role/CodeCommitWithdrawalRequestRole with iam credentials
2019/11/02 10:47:16 Using role ****************BXVV, expires in 14m59.859956s
2019/11/02 10:47:16 Setting subprocess env: AWS_DEFAULT_REGION=eu-west-1, AWS_REGION=eu-west-1
2019/11/02 10:47:16 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2019/11/02 10:47:16 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2019-11-02 10:47:16,855 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.271 Python/3.6.6 Darwin/18.7.0 botocore/1.12.123
2019-11-02 10:47:16,855 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sts', 'get-caller-identity', '--debug']
2019-11-02 10:47:16,856 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x109589158>
2019-11-02 10:47:16,856 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x108f44bf8>
2019-11-02 10:47:16,856 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x108fa0bf8>
2019-11-02 10:47:16,863 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/botocore/credentials.py", line 1676, in _get_provider_offset
    return [p.METHOD for p in self.providers].index(name)
ValueError: 'assume-role-with-web-identity' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/awscli/clidriver.py", line 213, in main
    self._emit_session_event(parsed_args)
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/awscli/clidriver.py", line 253, in _emit_session_event
    parsed_args=parsed_args)
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/botocore/session.py", line 671, in emit
    return self._events.emit(event_name, **kwargs)
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/awscli/customizations/assumerole.py", line 43, in inject_assume_role_provider_cache
    'assume-role-with-web-identity'
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/botocore/credentials.py", line 1672, in get_provider
    return self.providers[self._get_provider_offset(name)]
  File "/Users/fichtner/.pyenv/versions/3.6.6/lib/python3.6/site-packages/botocore/credentials.py", line 1678, in _get_provider_offset
    raise UnknownCredentialError(name=name)
botocore.exceptions.UnknownCredentialError: Credential named assume-role-with-web-identity not found.
2019-11-02 10:47:16,867 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Credential named assume-role-with-web-identity not found.
```

I do have the latest versions of aws-vault and aws-cli installed:
```
aws-vault v4.7.1
aws-cli/1.16.272 Python/3.7.5 Darwin/18.7.0 botocore/1.13.8
```

My ~/.aws/config looks like this:
```
[profile vera-git]
region=eu-west-1
source_profile=vera
role_arn=arn:aws:iam::753846010638:role/CodeCommitWithdrawalRequestRole
mfa_serial=arn:aws:iam::511237493963:mfa/vera
output=json

[profile vera]
region=eu-west-1
```

Running the same command via AWS CLI works:
```
$ aws --profile vera-git sts get-caller-identity
Enter MFA code for arn:aws:iam::511237493963:mfa/vera:
{
    "UserId": "AROA26SIPG3HPW7D7EVQ2:botocore-session-1572688538",
    "Account": "753846010638",
    "Arn": "arn:aws:sts::753846010638:assumed-role/CodeCommitWithdrawalRequestRole/botocore-session-1572688538"
}
```

I would really appreciate any hints on how to fix this error.

**Comment by Govinda-Fichtner** [comment]
What is also strange is that when I copy the AWS environment variables from a `aws-vault --debug exec vera-git -- env | grep AWS` command which does not produce any errors by the way and run `aws sts get-caller-identity` with those variables set everything works just fine.

**Comment by Govinda-Fichtner** [comment]
Trying the same with [awsudo](https://github.com/makethunder/awsudo) with the same `~/.aws/config` works:

```
awsudo -u vera-git aws sts get-caller-identity
Enter MFA code for arn:aws:iam::501237497963:mfa/vera:
{
    "UserId": "AROA26SIPG3HPW7D7EVQ2:botocore-session-1572691672",
    "Account": "753846010638",
    "Arn": "arn:aws:sts::753846010638:assumed-role/CodeCommitWithdrawalRequestRole/botocore-session-1572691672"
}
```

**Comment by jstewmon** [comment]
The debug output from the failed command with aws-vault has different versions of your toolchain than you later indicated:

```
2019-11-02 10:47:16,855 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.271 Python/3.6.6 Darwin/18.7.0 botocore/1.12.123
```

That version of botocore doesn't appear to support the `assume-role-with-web-identity` provider, which seems to have been [recently added](https://github.com/boto/botocore/commit/02df351ce8e857b32997e749d81effc4ba86bc22#diff-dcd72ae45553af71f1ceafb2d4ee5dcf) in version 1.13.8.

Maybe you [inadvertently activated](https://github.com/pyenv/pyenv-virtualenv#activate-virtualenv) an older version of the toolchain when you tried with aws-vault?

Please double-check on your side, and let us know if the issue persists with the expected toolchain versions.

**Comment by Govinda-Fichtner** [comment]
@jstewmon Good catch. Obviously I updated AWS CLI while trying to find the root of the problem without trying it with aws-vault again. It now seems to work. So because of the way the environment variables are set by aws-vault AWS CLI decides to use the `assume-role-with-web-identity` which only works with recents versions of AWS CLI? 

Maybe it makes sense to document this version in the aws-vault chapter about MFA and assume-role... 

Thanks for your help!

**Comment by jstewmon** [comment]
I did a little more digging and found that the issue seems to have been a release of aws-cli which may not have included a requisite bump of the required version of botocore:
https://github.com/aws/aws-cli/issues/4371

Since the issue was unrelated, I’m going to go ahead and close this issue.
